name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-backend-app-generic.yml@a24b2f08aebb7284e6b2c118eaeaa0fa9bec1d40
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      sonarOrganization: gridsuite
      sonarProjectKey: org.gridsuite:case-import-server
      dockerImage: docker.io/gridsuite/case-import-server
      dockerUsername: gridsuiteci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

